/**
 * Realistic mock data for development and demonstration
 * TODO PASS 2: Replace with real API calls
 */

export const mockTeams = [
  { id: 'team-1', name: 'Sales Team Alpha' },
  { id: 'team-2', name: 'Support Team Beta' },
];

export const mockAgents = [
  {
    id: 'agt-1',
    agentId: 'AGT001',
    agentName: 'Kiran Patel',
    teamName: 'Sales Team Alpha',
    ccPct: 85,
    scPct: 18,
    upPct: 28,
    fixedPct: 65,
    referralLeads: 25,
    referralShowups: 20,
    referralPaid: 15,
    referralAchievementPct: 85,
    totalLeads: 60,
    recoveredLeads: 22,
    unrecoveredLeads: 38,
    conversionPct: 36.7,
    weightedScore: 1.08,
    targetsHit: 3,
    status: 'above' as const,
  },
  {
    id: 'agt-2',
    agentId: 'AGT002',
    agentName: 'Aisha Khan',
    teamName: 'Sales Team Alpha',
    ccPct: 92,
    scPct: 20,
    upPct: 32,
    fixedPct: 72,
    referralLeads: 30,
    referralShowups: 25,
    referralPaid: 20,
    referralAchievementPct: 90,
    totalLeads: 70,
    recoveredLeads: 28,
    unrecoveredLeads: 42,
    conversionPct: 40,
    weightedScore: 1.18,
    targetsHit: 4,
    status: 'above' as const,
  },
  {
    id: 'agt-3',
    agentId: 'AGT003',
    agentName: 'Marcus Chen',
    teamName: 'Support Team Beta',
    ccPct: 75,
    scPct: 12,
    upPct: 20,
    fixedPct: 55,
    referralLeads: 18,
    referralShowups: 14,
    referralPaid: 10,
    referralAchievementPct: 72,
    totalLeads: 50,
    recoveredLeads: 15,
    unrecoveredLeads: 35,
    conversionPct: 30,
    weightedScore: 0.88,
    targetsHit: 1,
    status: 'warning' as const,
  },
  {
    id: 'agt-4',
    agentId: 'AGT004',
    agentName: 'Elena Rodriguez',
    teamName: 'Sales Team Alpha',
    ccPct: 70,
    scPct: 10,
    upPct: 18,
    fixedPct: 50,
    referralLeads: 15,
    referralShowups: 10,
    referralPaid: 6,
    referralAchievementPct: 65,
    totalLeads: 45,
    recoveredLeads: 12,
    unrecoveredLeads: 33,
    conversionPct: 26.7,
    weightedScore: 0.78,
    targetsHit: 0,
    status: 'below' as const,
  },
];

export const mockWeeklyData = [
  {
    week: 'Week 1',
    cc: 70,
    ccTarget: 20,
    sc: 12,
    scTarget: 3.75,
    up: 20,
    upTarget: 6.25,
    fixed: 55,
    fixedTarget: 15,
  },
  {
    week: 'Week 2',
    cc: 78,
    ccTarget: 26.7,
    sc: 15,
    scTarget: 5,
    up: 24,
    upTarget: 8.3,
    fixed: 60,
    fixedTarget: 20,
  },
  {
    week: 'Week 3',
    cc: 85,
    ccTarget: 40,
    sc: 18,
    scTarget: 7.5,
    up: 28,
    upTarget: 12.5,
    fixed: 65,
    fixedTarget: 30,
  },
  {
    week: 'Week 4',
    cc: 92,
    ccTarget: 80,
    sc: 20,
    scTarget: 15,
    up: 32,
    upTarget: 25,
    fixed: 72,
    fixedTarget: 60,
  },
];

export const mockKPIData = [
  {
    label: 'Class Consumption',
    value: 85,
    target: 80,
    change: '+5%',
    trend: [70, 75, 80, 85],
  },
  {
    label: 'Super-CC',
    value: 18,
    target: 15,
    change: '+20%',
    trend: [12, 14, 16, 18],
  },
  {
    label: 'Upgrade',
    value: 28,
    target: 25,
    change: '+12%',
    trend: [20, 23, 26, 28],
  },
  {
    label: 'Fixed',
    value: 65,
    target: 60,
    change: '+8%',
    trend: [55, 58, 62, 65],
  },
];

export const mockFunnelData = [
  { stage: 'Leads', value: 250 },
  { stage: 'Showups', value: 190 },
  { stage: 'Paid', value: 140 },
];

export const mockTeamRadarData = [
  { metric: 'CC', teamA: 85, teamB: 75, max: 100 },
  { metric: 'SC', teamA: 18, teamB: 12, max: 25 },
  { metric: 'UP', teamA: 28, teamB: 20, max: 35 },
  { metric: 'Fixed', teamA: 65, teamB: 55, max: 80 },
  { metric: 'Referral', teamA: 85, teamB: 72, max: 100 },
];

export const mockAlerts = [
  {
    id: 'alert-1',
    severity: 'warning' as const,
    agentName: 'Marcus Chen',
    teamName: 'Support Team Beta',
    message: 'Below target for 2 consecutive weeks',
    metric: 'Class Consumption',
    timestamp: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'alert-2',
    severity: 'critical' as const,
    agentName: 'Elena Rodriguez',
    teamName: 'Sales Team Alpha',
    message: 'Below target on 3 out of 4 metrics',
    metric: 'Overall Performance',
    timestamp: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'alert-3',
    severity: 'info' as const,
    agentName: 'Aisha Khan',
    teamName: 'Sales Team Alpha',
    message: 'Achieved all targets',
    metric: 'All Metrics',
    timestamp: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
  },
];
